Repository schubergphilis/terraform-aws-mcaf-landing-zone, pull requests merged in 2023-07, with the labels that each got.

#180 bug: ses-root-accounts-mail-forward s3 bucket solve ACL error
  README.md
  ses_accounts_mail_alias.tf
Labels: bug

#176 enhancement: Enable SecurityHub for management and logging account
  README.md
  data.tf
  kms.tf
  security_hub.tf
  versions.tf
Labels: bug, documentation, enhancement, feature

#182 enhancement: Adds log collection option for DD integration
  README.md
  datadog.tf
  variables.tf
Labels: feature

#184 bug: cis metrics filters get removed when upgrading to v0.26.0 or higher but not upgrading to security hub cis 1.4
  locals.tf
Labels: bug

#183 fix: Remove unused `files/okta/app_settings.json.tpl` file
  files/okta/app_settings.json.tpl
Labels: fix

#185 feature: Refactor AWS Security Hub configuration
  CHANGELOG.md
  README.md
  UPGRADING.md
  locals.tf
  security_hub.tf
  variables.tf
Labels: breaking, feature

#186 bug: aws security hub in management settings need to be removed to prevent overriding of values
  security_hub.tf
Labels: bug
