Repository schubergphilis/terraform-aws-mcaf-landing-zone, pull requests merged in 2024-01, with the labels that each got.

#196 breaking: Control Tower 3.0 support
  README.md
  account_audit.tf
  account_logging.tf
  data.tf
  files/sns/iam_activity_topic_policy.json.tpl
  files/sns/security_hub_topic_policy.json.tpl
  iam_activity_logging.tf
Labels: breaking

#197 enhancement: Enable AWS Audit Manager
  README.md
  audit_manager.tf
  kms.tf
  organizations_policy.tf
  variables.tf
Labels: feature

#198 fix: global allowed region permissions for s3 logging & quicksight
  files/organizations/allowed_regions.json.tpl
Labels: bug, fix
